version: '3.7'

name: kerosine-nodejs-boilerplate-api
services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: template-api-proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - api-network
  broker:
    image: oresoftware/live-mutex-broker:0.2.24
    container_name: template-api-lock-broker
    ports:
      - '6970:6970'
    environment:
      - live_mutex_port=6970
      - live_mutex_host=0.0.0.0
    restart: 'unless-stopped'
    networks:
      - api-network
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    image: ocdkerosine/nodejs-template-api:latest
    container_name: template-api
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - api-network

networks:
  api-network:
    name: template-network
    driver: bridge

volumes:
  api-data:
    name: template-data
    driver: local

#docker-compose config > docker-compose-resolved.yaml
#kompose convert -f docker-compose-resolved.yaml --volumes hostPath -o kubernetes --build local
#docker-compose -p paylot-api up --build
#kubectl get deploy
#kubectl delete deploy <deployment name>
#kubectl proxy
